language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
    - "pypy3"
matrix:
    fast_finish: true
    allow_failures:
        - python: "3.3"
        - python: "3.4"
        - python: "pypy3"
        - python: "pypy"
before_install:
    - sudo apt-get update -y
    - sudo apt-get -y install build-essential cmake libtool libwebp-dev openexr unzip python-dev aptitude
    - pip install setuptools

    - cd ~
    - wget https://github.com/uclouvain/openjpeg/archive/version.2.0.1.tar.gz
    - tar xf version.2.0.1.tar.gz
    - cd openjpeg-version.2.0.1
    - cmake .
    - make
    - sudo make install
    - sudo make clean

    - sudo ldconfig /usr/lib

install:
    # install aptitude packages
    - cd ~/build/thumbor/thumbor-plugins
    - LDFLAGS=-lm sudo aptitude install -y $(< requirements)
    - make setup
script:
    - make test
