language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
matrix:
    fast_finish: true
    allow_failures:
        - python: "3.3"
        - python: "3.4"
        - python: "pypy3"
install: "pip install thumbor"
script: nosetests
